---

- hosts: tag_Role_bootapp
  tasks:
    - docker_container:
          name: "bootapp{{ item }}"
          recreate: yes
          image: marcopaga/cxf-spring-boot-starter-system-tests
      with_sequence: count=4
    - docker_container:
        name: loadbalancer
        image: nginx:alpine

- hosts: all
  tasks:
    - command: echo this is run on every server
